### ISSUE TITLE
Milestone 1: EDA Notebook and project doc on operate first website

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#34]
We want to make sure that the work we are doing for the OCP CI data analysis is easy to follow and interact with so that we can get more contributions from other Data Scientists. 

Acceptance Criteria:

Include well written and polished version of the following on operate-first.github.io

- [x] Project Document: Outlining project goal 
- [x] Rendered notebook on initial testgrid EDA
- [x] Rendered notebook on in-depth testgrid EDA
- [x] Polish all content, focused on ease of use by new contributors

**Comment by MichaelClifford** [comment]
See [this PR](https://github.com/operate-first/operate-first.github.io/pull/91)to confirm above items have been included on the [op1st website](https://operate-first.github.io/operate-first/)
