### ISSUE TITLE
[EPIC] Build Documentation from a k8s contributor standpoint

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#340]
## As a Kubernetes contributor, I want to

- Use AI4CI to monitor and visualize builds.
- Build a more intelligent TestGrid visualization platform.

We want to create a clear pathway for k8s contributors landing on the project.

Acceptance Criteria:

- [ ] Modify Getting Started Page to have a clear path for k8s contributors.
- [ ] Show dashboards visualizing KPI metrics.
- [ ] Display an example of an end-to-end workflow starting with TestGrid/Prow data source to the KPI dashboard.

**Comment by MichaelClifford** [comment]
:+1:

**Comment by oindrillac** [comment]
closed by 385
