### ISSUE TITLE
Use MOC OpenStack for long term data storage [EPIC]

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#442]
We have been requesting a location to host public data for some time now (https://github.com/operate-first/support/issues/23) and the consensuses decision has been to use MOC Openstack accounts for storage rather than something on one of the opf clusters as they are more ephemeral (https://github.com/open-infrastructure-labs/ops-issues/issues/33).   

To that end, I have created a public bucket specifically for AI4CI project here: https://kzn-swift.massopen.cloud/swift/v1/ai4ci/  
This bucket *should* allow for users to read data without restriction, but only users with credentials can write/delete data.  

Here are the docs for interacting with the bucket:
https://docs.massopen.cloud/en/latest/openstack/Object-Storage.html

Please reach out to me if you are working on this and I can provide credentials or add you to the openstack project managing the bucket. 

### We should migrate the existing ai4ci work such that all data is stored here, rather than on the opf-datacatalog bucket on smaug.

Acceptance Criteria: 

- [ ] Confirm data can be publicly read, but credentials are required to write/delete. Create short notebook to demo interaction
- [ ] Confirm Trino/Superset connections can be maintained through this bucket. Give demo to team 
- [ ] Move all existing relevant data from opf-datacatalog to ai4ci.
- [ ] Update all notebooks and pipelines to target this bucket.

**Comment by antter** [comment]
Working on this first point:

https://github.com/aicoe-aiops/ocp-ci-analysis/issues/443
