### ISSUE TITLE
[EPIC] Present GitHub Time to Merge ML Prob at DevConf.CZ

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#452]
As session presenters for the Github Time to Merge ML Model at DevConf.CZ, we want to make sure that the project and its contents are ready for consumption by an external audience.

- [x] Create an outline and come up with slides for the session.
- [x] Come up with Demo outline and record the demo.
- [x] Develop a dashboard for Github repo/PR metrics. (#453)
- [x] Fine tune/polish repository and website content to make user onboarding seamless.
- [ ] Conduct practice/feedback session with internal team before devconf.cz talk.

**Comment by oindrillac** [comment]
Presented talk at DevConf.CZ
[Youtube Video](https://youtu.be/bg-fZ7KGsbw) | [Slides](https://slides.com/chauhankaranraj/unconvering-insights-from-your-github)
